
const DK='ct_v2',$=s=>document.querySelector(s);
const DEF={ob:0,set:{name:'',type:'regular',cyc:28,per:5,theme:'light',pin:null,track:[],notif:false,remind:false},periods:[],daily:{},custom:[],journal:{},meds:[]};
let S;try{S=JSON.parse(localStorage.getItem(DK))}catch(e){}S=Object.assign(JSON.parse(JSON.stringify(DEF)),S||{});
if(!S.v3){S.set.theme='light';S.v3=1}
S.preg=S.preg||{on:false,lmp:'',notes:[]};S.rem=S.rem||[];
const save=()=>{try{localStorage.setItem(DK,JSON.stringify(S))}catch(e){toast('Storage full or unavailable.')}};
const pad=n=>String(n).padStart(2,'0'),d2s=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,s2d=s=>new Date(s+'T00:00:00'),today=()=>d2s(new Date()),addD=(s,n)=>{const d=s2d(s);d.setDate(d.getDate()+n);return d2s(d)},diff=(a,b)=>Math.round((s2d(b)-s2d(a))/864e5);
const fs=(s,o={month:'short',day:'numeric'})=>s2d(s).toLocaleDateString(undefined,o),esc=t=>String(t).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('on');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('on'),2200)}
function sheet(h){$('#shb').innerHTML=h;$('#sh').classList.add('on')}function shut(){$('#sh').classList.remove('on')}
$('#sh').onclick=e=>{if(e.target.id==='sh')shut()};
function theme(){const t=S.set.theme,l=t==='light'||(t==='system'&&matchMedia('(prefers-color-scheme:light)').matches);document.documentElement.dataset.t=l?'light':'dark'}
/* ---- cycle engine ---- */
function cy(){const st=S.periods.map(p=>p.startDate).sort(),lens=[];for(let i=1;i<st.length;i++)lens.push(diff(st[i-1],st[i]));
const rec=lens.slice(-6),avg=rec.length?Math.round(rec.reduce((a,b)=>a+b,0)/rec.length):S.set.cyc,so=[...rec].sort((a,b)=>a-b),med=so.length?so[Math.floor(so.length/2)]:null;
const mn=rec.length?so[0]:null,mx=rec.length?so[so.length-1]:null,pl=S.periods.filter(p=>p.endDate).map(p=>diff(p.startDate,p.endDate)+1),ap=pl.length?Math.round(pl.reduce((a,b)=>a+b,0)/pl.length):S.set.per;
const irr=S.set.type!=='regular'||(rec.length>1&&mx-mn>7);return{st,lens,avg,med,mn,mx,ap,irr,last:st[st.length-1]||null,n:st.length}}
function est(){const c=cy();if(!c.last)return null;const l=c.irr&&c.lens.length>=2?[c.mn,c.mx]:[c.avg,c.avg];return{lo:addD(c.last,l[0]-(c.irr?0:0)),hi:addD(c.last,l[1]+(c.irr?2:0)),range:c.irr&&c.lens.length>=2,enough:c.lens.length>=2}}
function pDays(){const s=new Set();S.periods.forEach(p=>{const e=p.endDate||addD(p.startDate,S.set.per-1);for(let d=p.startDate;d<=e;d=addD(d,1))s.add(d)});return s}
function eDays(){const s=new Set(),e=est();if(!e)return s;for(let d=e.lo;d<=addD(e.hi,e.range?0:S.set.per-1);d=addD(d,1))s.add(d);return s}
/* ---- router ---- */
const ico=p=>`<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${p}</svg>`;
const TABS=[['home',ico('<path d="M4 11l8-7 8 7v8a1 1 0 0 1-1 1h-4v-6h-6v6H5a1 1 0 0 1-1-1z"/>'),'Home'],['cal',ico('<rect x="4" y="5" width="16" height="15" rx="3"/><path d="M8 3v4M16 3v4M4 10h16"/>'),'Calendar'],['ins',ico('<path d="M4 19h16"/><path d="M6 15l4-4 3 3 5-6"/>'),'Insights'],['jour',ico('<path d="M6 4h10a2 2 0 0 1 2 2v14H8a2 2 0 0 1-2-2z"/><path d="M9 9h6M9 13h4"/>'),'Journal'],['more',ico('<circle cx="6" cy="12" r="1.3" fill="currentColor"/><circle cx="12" cy="12" r="1.3" fill="currentColor"/><circle cx="18" cy="12" r="1.3" fill="currentColor"/>'),'More']];let cur='home',arg=null,hist=[];
const PARENT={preg:'more',sum:'more',log:'home',sym:'home',pcos:'ins',life:'more',med:'more',learn:'more',set:'more',sub:'more'};
function go(n,a,back){if(!back&&cur!==n)hist.push([cur,arg]);cur=n;arg=a===undefined?null:a;render()}
function back(){const h=hist.pop()||['home',null];cur=h[0];arg=h[1];render()}
function render(){theme();const t=PARENT[cur]||cur;$('#nav').innerHTML=TABS.map(x=>`<button class="${x[0]===t?'a':''}" ${x[0]===t?'aria-current="page"':''} onclick="hist=[];go('${x[0]}')" aria-label="${x[2]}"><span class="ni">${x[1]}</span><span class="nl">${x[2]}</span></button>`).join('');$('#nav').style.display=cur==='lock'||cur==='ob'?'none':'flex';const v=$('#view');v.innerHTML=V[cur](arg);v.scrollTop=0;v.style.animation='none';v.offsetHeight;v.style.animation='';const ta=v.querySelector('.tabs .ch.s');if(ta)ta.parentElement.scrollLeft=Math.max(0,ta.offsetLeft-16)}
const hd=(t,r='')=>`<div class="tp"><div style="display:flex;align-items:center"><button class="ic" onclick="back()" aria-label="Back">←</button><h2>${t}</h2></div>${r}</div>`;
const SY=['Cramps','Headache','Backache','Bloating','Breast tenderness','Nausea','Fatigue','Acne','Skin changes','Hair changes','Pelvic discomfort'],EM=['Calm','Happy','Irritated','Sad','Anxious','Low energy','Stressed'],MOODS=['Great','Good','Okay','Tired','Sad','Anxious','Stressed'];
const dr=d=>(S.daily[d]=S.daily[d]||{date:d,symptoms:[],mood:null,pain:null,flow:null,notes:'',stress:null,sleep:null,water:null,exercise:null,weight:null});
/* ---- onboarding ---- */
const OB={t:[],ty:'regular',dt:null,m:new Date(),cyc:28,per:5};
function obNext(){S.ob++;render()}function obSkip(){finish(true)}
function finish(skip){if(!skip){S.set.type=OB.ty;S.set.track=OB.t;S.set.cyc=OB.cyc;S.set.per=OB.per;if(OB.dt)S.periods.push({id:'p'+Date.now(),startDate:OB.dt,endDate:addD(OB.dt,OB.per-1),flow:'medium',symptoms:[],notes:'',createdAt:Date.now(),updatedAt:Date.now()})}S.ob=99;save();cur='home';render()}
function obCal(){const y=OB.m.getFullYear(),m=OB.m.getMonth(),o=(new Date(y,m,1).getDay()+6)%7,n=new Date(y,m+1,0).getDate();let h=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<div class="w">${d}</div>`).join('')+'<div></div>'.repeat(o);for(let i=1;i<=n;i++){const s=`${y}-${pad(m+1)}-${pad(i)}`,f=s>today();h+=`<button class="dy ${OB.dt===s?'p':''}" ${f?'disabled style="opacity:.3"':''} onclick="OB.dt='${s}';render()">${i}</button>`}
return`<div class="c"><div class="tp" style="margin:0 0 8px"><button class="ic" onclick="OB.m.setMonth(OB.m.getMonth()-1);render()" aria-label="Previous month">‹</button><b>${OB.m.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</b><button class="ic" onclick="OB.m.setMonth(OB.m.getMonth()+1);render()" aria-label="Next month">›</button></div><div class="g7">${h}</div></div>`}
const step=(k,v,mn,mx,u)=>`<div class="c" style="display:flex;align-items:center"><button class="ic" onclick="OB.${k}=Math.max(${mn},OB.${k}-1);render()" aria-label="Decrease">−</button><div class="num">${OB[k]}</div><button class="ic" onclick="OB.${k}=Math.min(${mx},OB.${k}+1);render()" aria-label="Increase">+</button></div><p style="text-align:center">${u}</p>`;
const foot=(l='Continue')=>`<div class="sp"></div><button class="b" onclick="obNext()">${l}</button><button class="b g" onclick="obSkip()">Skip</button>`;
const TR=['Periods','Symptoms','Mood','PCOS / Irregular cycles','Fertility','Pregnancy','Lifestyle'],TY=[['regular','Regular','around the same time each month'],['irregular','Irregular','varies a lot'],['pcos','I have PCOS','confirmed or suspected'],['unsure',"I'm not sure",'']];
const OBS=[()=>`<div class="ob wl" onclick="obNext()"><div class="wl-t"></div><div class="wl-m"><span class="hx" aria-hidden="true"></span><h1>Your Health<br>Our Priority</h1><p>Track your cycle, understand your body, feel more in control.</p></div><div class="wl-b"><div class="prog" aria-hidden="true"><i></i></div><button class="b" onclick="event.stopPropagation();obNext()">Continue</button><small>Private &middot; stored only on this device</small></div></div>`,
()=>`<div class="ob"><h2 style="margin-top:6px">Let's get to know you</h2><p>This helps us give you a more personalised experience.</p><div style="flex:1;display:grid;place-items:center;padding:8px 0"><svg viewBox="0 0 280 210" width="100%" style="max-width:300px" role="img" aria-label="Illustration of a hospital building"><ellipse cx="140" cy="112" rx="118" ry="88" fill="var(--halo)"/><line x1="14" y1="184" x2="266" y2="184" stroke="var(--ac)" stroke-width="2" stroke-linecap="round"/><g fill="var(--cd)" stroke="var(--ac)" stroke-width="2" stroke-linejoin="round"><rect x="30" y="118" width="62" height="66" rx="4"/><rect x="188" y="118" width="62" height="66" rx="4"/><rect x="90" y="72" width="100" height="112" rx="5"/></g><g fill="var(--sf)" stroke="var(--ac2)" stroke-width="1.5"><rect x="42" y="132" width="14" height="16" rx="2"/><rect x="66" y="132" width="14" height="16" rx="2"/><rect x="42" y="158" width="14" height="16" rx="2"/><rect x="66" y="158" width="14" height="16" rx="2"/><rect x="200" y="132" width="14" height="16" rx="2"/><rect x="224" y="132" width="14" height="16" rx="2"/><rect x="200" y="158" width="14" height="16" rx="2"/><rect x="224" y="158" width="14" height="16" rx="2"/><rect x="102" y="112" width="16" height="18" rx="2"/><rect x="132" y="112" width="16" height="18" rx="2"/><rect x="162" y="112" width="16" height="18" rx="2"/><rect x="102" y="138" width="16" height="18" rx="2"/><rect x="162" y="138" width="16" height="18" rx="2"/></g><path d="M124 184v-26a16 16 0 0 1 32 0v26z" fill="var(--sf)" stroke="var(--ac)" stroke-width="2"/><line x1="140" y1="144" x2="140" y2="184" stroke="var(--ac2)" stroke-width="1.5"/><rect x="112" y="98" width="56" height="5" rx="2.5" fill="var(--ac)"/><g fill="var(--ac)"><rect x="129" y="34" width="22" height="7" rx="2" transform="translate(0,14)"/><rect x="136.5" y="41" width="7" height="22" rx="2"/></g><circle cx="140" cy="52" r="20" fill="none" stroke="var(--ac2)" stroke-width="1.5" opacity=".6"/><path d="M262 184c0-14 10-14 10 0M8 184c0-12 8-12 8 0" stroke="var(--ac2)" stroke-width="2" fill="none" stroke-linecap="round"/></svg></div><button class="b" onclick="obNext()">Get Started</button><button class="b g" onclick="obSkip()">Skip</button></div>`,
()=>`<div class="ob"><h2>What would you like to track?</h2><p>You can always change this later.</p><div style="margin-top:12px">${TR.map((t,i)=>`<button class="r ${OB.t.includes(t)?'s':''}" onclick="const k=OB.t.indexOf('${t}');k>-1?OB.t.splice(k,1):OB.t.push('${t}');render()" aria-pressed="${OB.t.includes(t)}"><span>${t}</span><span class="x" style="color:var(--ac);font-weight:700">${OB.t.includes(t)?'✓':'›'}</span></button>`).join('')}</div>${foot()}</div>`,
()=>`<div class="ob"><h2>How would you describe your cycles?</h2><div style="margin-top:12px">${TY.map(t=>`<button class="r ${OB.ty===t[0]?'s':''}" style="padding:16px" onclick="OB.ty='${t[0]}';render()"><span>${t[1]}${t[2]?'<br><small>'+t[2]+'</small>':''}</span><span class="x" style="color:var(--ac);font-weight:700">${OB.ty===t[0]?'✓':''}</span></button>`).join('')}</div>${foot()}</div>`,
()=>`<div class="ob"><h2>When did your last period start?</h2><div style="margin-top:12px">${obCal()}</div>${foot()}</div>`,
()=>`<div class="ob"><h2>How long is your usual cycle?</h2><p>The number of days from the start of one period to the start of the next. This is only a starting estimate.</p><div style="margin-top:10px">${step('cyc',0,15,90,'days (optional)')}</div><h3 style="margin-top:10px">How long does your period usually last?</h3>${step('per',0,1,14,'days (optional)')}<div class="sp"></div><button class="b" onclick="finish()">Continue</button><button class="b g" onclick="obSkip()">Skip</button></div>`];
/* ---- home ---- */
function ring(f,big,sub){const r=62,C=2*Math.PI*r;return`<svg viewBox="0 0 160 160" width="170" height="170" role="img" aria-label="${big} ${sub}"><circle cx="80" cy="80" r="${r}" fill="none" stroke="var(--bd)" stroke-width="9"/><circle cx="80" cy="80" r="${r}" fill="none" stroke="var(--ac)" stroke-width="9" stroke-linecap="round" stroke-dasharray="${C}" stroke-dashoffset="${C*(1-f)}" transform="rotate(-90 80 80)" style="transition:stroke-dashoffset .8s"/><text x="80" y="62" text-anchor="middle" fill="var(--t2)" font-size="11">Cycle Day</text><text x="80" y="94" text-anchor="middle" fill="var(--tx)" font-size="36" font-family="Georgia">${big}</text></svg>`}
function nextTxt(){const e=est(),c=cy();if(!e)return'Log your first period to start seeing your cycle.';if(!e.enough)return`Keep logging your cycles to improve estimates.<br><small>Rough estimate from your set cycle length: around ${fs(e.lo)}</small>`;
if(e.range)return`Estimated: your next period may arrive around ${fs(e.lo)}–${fs(e.hi)}.<br><small>Your cycle has varied recently, so this estimate may change.</small>`;const d=diff(today(),e.lo);return d>=0?`${d} day${d==1?'':'s'} until estimated period<br><small>Estimated, not confirmed</small>`:`Estimated period date has passed by ${-d} day${d==-1?'':'s'}<br><small>Log it when it starts to keep estimates accurate</small>`}
function hi(){const h=new Date().getHours();return h<12?'Good morning,':h<18?'Good afternoon,':'Good evening,'}
const TQ=[['mood','☺','Mood'],['flow','◍','Flow'],['pain','✚','Pain'],['sym','≡','Symptoms']];
V={home(){const c=cy(),day=c.last?diff(c.last,today())+1:null,e=est(),len=e&&e.enough&&!e.range?c.avg:(c.irr&&c.mx?c.mx:S.set.cyc);
const t=dr(today());return`<div class="tp"><div style="display:flex;gap:10px;align-items:center"><div style="width:38px;height:38px;border-radius:50%;background:var(--sf);border:1px solid var(--bd);display:grid;place-items:center">${esc((S.set.name||'Y')[0].toUpperCase())}</div><div><small>${hi()}</small><h2 style="font-size:18px">${esc(S.set.name||'there')}</h2></div></div><button class="ic" onclick="go('sub','notif')" aria-label="Reminders">◎</button></div>
<div class="c" style="text-align:center;padding:18px 14px">${ring(day?Math.min(day/len,1):0,day||'–','')}<p style="color:var(--tx)">${nextTxt()}</p></div>
<h3>Today</h3><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:12px">${TQ.map(q=>`<button class="r" style="flex-direction:column;gap:4px;padding:10px 4px;text-align:center;margin:0;font-size:11px" onclick="quick('${q[0]}')"><span class="i">${q[1]}</span>${q[2]}${(q[0]==='mood'&&t.mood)||(q[0]==='pain'&&t.pain)||(q[0]==='flow'&&t.flow)?`<small>${esc(t.mood&&q[0]==='mood'?t.mood:q[0]==='pain'?t.pain:t.flow)}</small>`:''}</button>`).join('')}</div>
<h3>Quick actions</h3><div style="display:flex;gap:8px"><button class="b o" style="margin:0" onclick="go('log')">Log period</button><button class="b o" style="margin:0" onclick="go('sym',today())">Add symptom</button></div><button class="b g" style="margin-top:4px" onclick="pastDay()">Missed a day? Log a different date</button>
<div class="c" style="margin-top:12px"><h3>Recent symptoms</h3>${(()=>{const k=Object.keys(S.daily).filter(d=>S.daily[d].symptoms.length).sort().reverse().slice(0,3);return k.length?k.map(d=>`<p><b style="color:var(--tx)">${fs(d)}</b> · you logged ${S.daily[d].symptoms.map(esc).join(', ')}</p>`).join(''):'<p>Nothing logged recently. Use “Add symptom” to start.</p>'})()}</div>`},
/* ---- calendar ---- */
cal(){const m=cal.m=cal.m||new Date(new Date().getFullYear(),new Date().getMonth(),1),y=m.getFullYear(),mo=m.getMonth(),o=(new Date(y,mo,1).getDay()+6)%7,n=new Date(y,mo+1,0).getDate(),P=pDays(),E=eDays(),F=fert(),c=cy();
let h=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<div class="w">${d}</div>`).join('')+'<div></div>'.repeat(o);for(let i=1;i<=n;i++){const s=`${y}-${pad(mo+1)}-${pad(i)}`,r=S.daily[s],lg=r&&(r.symptoms.length||r.mood||r.pain||r.notes||r.flow||r.spot);h+=`<button class="dy ${P.has(s)?'p':E.has(s)?'e':F.has(s)?'f':''} ${s===today()?'t':''}" onclick="dayS('${s}')" aria-label="${fs(s)}${P.has(s)?', period logged':E.has(s)?', estimated period':F.has(s)?', estimated fertile window':''}">${i}${lg?'<i></i>':''}</button>`}
return`<div class="tp"><h2>Calendar</h2><button class="ic" onclick="go('log')" aria-label="Log period">+</button></div><div class="c"><div class="tp" style="margin:0 0 8px"><button class="ic" onclick="cal.m.setMonth(cal.m.getMonth()-1);render()" aria-label="Previous month">‹</button><b>${m.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</b><button class="ic" onclick="cal.m.setMonth(cal.m.getMonth()+1);render()" aria-label="Next month">›</button></div><div class="g7">${h}</div><p style="margin-top:10px;font-size:11px">● Logged period &nbsp; ◌ Estimated (dashed) &nbsp; ○ Today &nbsp; · Other logged data${S.set.fert?' &nbsp; ▫ Estimated fertile window (may be unreliable)':''}</p></div>
<div class="c"><div class="tp" style="margin-bottom:8px"><h3 style="margin:0">Cycle history</h3><button class="ic" style="font-size:12px;color:var(--ac2)" onclick="go('ins')">See all</button></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><div><small>Avg. cycle length</small><h2>${c.lens.length?c.avg+' days':'–'}</h2></div><div><small>Avg. period length</small><h2>${c.n?c.ap+' days':'–'}</h2></div></div>${c.n?'':'<p>No cycle history yet. Log your first period.</p>'}</div>`},
/* ---- log period ---- */
log(id){const p=LP.p=LP.p&&LP.id===id?LP.p:(LP.id=id,id?JSON.parse(JSON.stringify(S.periods.find(x=>x.id===id))):{startDate:today(),endDate:'',flow:'medium',symptoms:[],notes:''});
return hd(id?'Edit period':'Log period')+`<div class="c"><label style="margin:0">Start date</label><input type="date" id="ls" max="${today()}" value="${p.startDate}" onchange="LP.p.startDate=this.value"><label>End date</label><input type="date" id="le" value="${p.endDate||''}" onchange="LP.p.endDate=this.value"></div><h3>Flow level</h3><div style="display:flex;gap:8px">${['light','medium','heavy'].map(f=>`<button class="r ${p.flow===f?'s':''}" style="justify-content:center;margin:0" onclick="LP.p.flow='${f}';LP.keep=1;render()">${f[0].toUpperCase()+f.slice(1)}</button>`).join('')}</div><h3 style="margin-top:14px">Symptoms (optional)</h3><div>${[...SY.slice(0,6),...S.custom].map(s=>`<button class="ch ${p.symptoms.includes(s)?'s':''}" onclick="tg(LP.p.symptoms,'${esc(s).replace(/'/g,"\\'")}');render()">${esc(s)}</button>`).join('')}</div><button class="ch" onclick="addCustom(s=>{LP.p.symptoms.push(s);render()})">+ Add symptom</button><label>Notes (optional)</label><textarea id="ln" rows="2" oninput="LP.p.notes=this.value">${esc(p.notes||'')}</textarea><button class="b" onclick="saveP()">Save</button>${id?`<button class="b d" onclick="sheet('<h3>Delete this period?</h3><p>This cannot be undone.</p><button class=\\'b\\' onclick=\\'delP(\\"${id}\\")\\'>Delete</button><button class=\\'b g\\' onclick=\\'shut()\\'>Cancel</button>')">Delete period</button>`:''}`},
/* ---- symptoms ---- */
sym(d){d=d||today();sym.d=d;sym.t=sym.t||'p';const r=dr(d),L=sym.t==='p'?[...SY,...S.custom]:EM;
return hd('Symptoms')+`<input type="date" max="${today()}" value="${d}" aria-label="Date for these symptoms" style="margin:-4px 0 12px" onchange="if(this.value&&this.value<=today())go('sym',this.value);else{toast('Choose today or an earlier date.');render()}"><div class="seg"><button class="${sym.t==='p'?'s':''}" onclick="sym.t='p';render()">Physical</button><button class="${sym.t==='e'?'s':''}" onclick="sym.t='e';render()">Emotional</button></div>${L.map(s=>`<button class="r ${r.symptoms.includes(s)?'s':''}" onclick="tg(dr('${d}').symptoms,'${esc(s).replace(/'/g,"\\'")}');save();render()" aria-pressed="${r.symptoms.includes(s)}"><span class="i">${r.symptoms.includes(s)?'✓':'•'}</span>${esc(s)}<span class="x">${r.symptoms.includes(s)?'':'›'}</span></button>${r.symptoms.includes(s)?sevRow(d,s,r):''}`).join('')}<button class="r" onclick="addCustom(s=>{dr('${d}').symptoms.push(s);save();render()})"><span class="i">+</span>Add custom symptom</button>`},
/* ---- insights ---- */
ins(){ins.t=ins.t||'o';const c=cy(),T=[['o','Overview'],['c','Cycles'],['s','Symptoms'],['m','Mood'],['t','Trends']];let b='';
const symF=()=>{const f={};Object.values(S.daily).forEach(r=>r.symptoms.forEach(s=>f[s]=(f[s]||0)+1));return Object.entries(f).sort((a,b)=>b[1]-a[1])};
if(ins.t==='o'){b=`<div class="c"><h3>Cycle pattern</h3>${c.lens.length<2?'<p>More data is needed before patterns can be shown. Log at least three period start dates.</p>':`<p>Based on your logged history, your cycle lengths were ${c.lens.slice(-4).join(', ')} days.${c.irr?' Your cycles have varied over recent months. This can be common, especially with irregular cycles or PCOS. Consider discussing this pattern with a healthcare professional.':' Your logged cycles have been fairly consistent.'}</p>`}${chart(c.lens.slice(-6))}</div><div class="c"><h3>Your symptoms</h3>${(()=>{const f=symF()[0];return f?`<p>You logged ${esc(f[0].toLowerCase())} on ${f[1]} day${f[1]>1?'s':''}.</p>`:'<p>No symptoms logged yet.</p>'})()}<button class="ic" style="font-size:12px;color:var(--ac2);padding:4px 0" onclick="ins.t='s';render()">View details</button></div>`+(c.irr?`<button class="r" onclick="go('pcos')"><span class="i">◎</span>PCOS / Irregular cycle view<span class="x">›</span></button>`:'')}
else if(ins.t==='c'){b=c.lens.length?`<div class="c"><h3>Cycle statistics</h3>${[['Average cycle',c.avg+' days'],['Median',c.med+' days'],['Shortest',c.mn+' days'],['Longest',c.mx+' days'],['Average period',c.ap+' days'],['Range of variation',(c.mx-c.mn)+' days']].map(x=>`<div style="display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid var(--bd)"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>`+bars(c.lens.slice(-6).reverse()):'<div class="c"><p>No cycle history yet. Log your first period to start seeing patterns.</p></div>'}
else if(ins.t==='s'){const f=symF();b=f.length?`<div class="c"><h3>Symptom frequency</h3>${f.slice(0,8).map(x=>`<div style="margin-bottom:8px"><small>${esc(x[0])} · ${x[1]} day${x[1]>1?'s':''}</small><div class="bar"><i style="width:${x[1]/f[0][1]*100}%"></i></div></div>`).join('')}</div>`:'<div class="c"><p>No symptoms logged yet.</p></div>'}
else if(ins.t==='t'){b=trends()}
else{const f={};Object.values(S.daily).forEach(r=>r.mood&&(f[r.mood]=(f[r.mood]||0)+1));const e=Object.entries(f).sort((a,b)=>b[1]-a[1]);b=e.length?`<div class="c"><h3>Mood distribution</h3>${e.map(x=>`<div style="margin-bottom:8px"><small>${x[0]} · ${x[1]}</small><div class="bar"><i style="width:${x[1]/e[0][1]*100}%"></i></div></div>`).join('')}</div>`:'<div class="c"><p>No moods logged yet.</p></div>'}
return`<div class="tp"><h2>Insights</h2></div><div class="tabs">${T.map(t=>`<button class="ch ${ins.t===t[0]?'s':''}" onclick="ins.t='${t[0]}';render()">${t[1]}</button>`).join('')}</div>${b}<div class="c"><p>Estimates and patterns come from your own logs and are not a diagnosis. If something feels unusual for you, consider speaking with a healthcare professional.</p></div>`},
pcos(){const c=cy();return hd('PCOS / Irregular Cycle')+`<div class="c"><small>Cycle type</small><h2 style="font-size:18px">${{regular:'Regular',irregular:'Irregular',pcos:'PCOS / Irregular',unsure:'Not sure yet'}[S.set.type]}</h2><p>Predictions may be less precise. That's okay — you're not alone.</p></div><div class="c"><h3>Your recent cycles</h3>${c.lens.length?bars(c.lens.slice(-6).reverse(),1)+`<p>Your cycles have varied between ${c.mn} and ${c.mx} days across these logged periods.</p>`:'<p>No cycle history yet. Log your first period to start seeing patterns.</p>'}</div><div class="c"><h3>Track more for better insights</h3><p>Log symptoms, lifestyle and medication to see detailed trends. This screen does not diagnose any condition.</p></div>`},
/* ---- journal ---- */
jour(){const d=jour.d||today(),e=S.journal[d]||{mood:null,text:''};jour.m=jour.m===undefined?e.mood:jour.m;const q=(jour.q||'').toLowerCase(),L=Object.values(S.journal).filter(x=>!q||(x.text+x.mood+x.date).toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date));
return`<div class="tp"><h2>Journal</h2><button class="ic" onclick="jour.s=!jour.s;render()" aria-label="Search">⌕</button></div>${jour.s?`<input placeholder="Search entries" value="${esc(jour.q||'')}" oninput="jour.q=this.value;jl()" style="margin-bottom:10px" autofocus>`:''}<div class="c"><input type="date" value="${d}" max="${today()}" onchange="jour.d=this.value;jour.m=undefined;render()"><h3 style="margin-top:12px">How are you feeling today?</h3><div>${MOODS.map(m=>`<button class="ch ${jour.m===m?'s':''}" onclick="jour.m='${m}';jour.t=document.getElementById('jt').value;render();document.getElementById('jt').value=jour.t">${m}</button>`).join('')}</div><label>Notes (optional)</label><textarea id="jt" rows="5" placeholder="Write something…">${esc(e.text)}</textarea><button class="b" onclick="saveJ()">Save</button>${S.journal[d]?`<button class="b d" onclick="delJ('${d}')">Delete entry</button>`:''}</div><h3>Previous entries</h3><div id="jl">${jlist(L)}</div>`},
/* ---- more ---- */
more(){return`<div class="tp"><h2>More</h2></div>${[['life','Lifestyle','☾'],['med','Medication & Supplements','✚'],['sum','Doctor summary','▤'],...(S.set.preg?[['preg','Pregnancy','◔']]:[]),['learn','Learn','▤'],['set','Settings','⚙']].map(x=>`<button class="r" onclick="go('${x[0]}')"><span class="i">${x[2]}</span>${x[1]}<span class="x">›</span></button>`).join('')}<div class="c" style="margin-top:12px"><h3>When to seek medical help</h3><p>If something feels unusual for you or you are concerned, consider speaking with a healthcare professional. This includes unusually severe pain, very heavy bleeding, fainting or dizziness with bleeding, symptoms that are worsening or interfering with daily life, or a very long absence of periods.</p></div>`},
/* ---- lifestyle ---- */
life(){const r=dr(life.d=life.d||today()),I=[['sleep','Sleep','h','☾'],['water','Water','L','◍'],['exercise','Exercise','min','↗'],['weight','Weight','kg','◇']];
return hd('Lifestyle')+`<input type="date" max="${today()}" value="${life.d}" aria-label="Date" style="margin:-4px 0 12px" onchange="if(this.value&&this.value<=today()){life.d=this.value;render()}else{toast('Choose today or an earlier date.');render()}">`+I.map(i=>`<button class="r" onclick="ask('${i[0]}','${i[1]}','${i[2]}')"><span class="i">${i[3]}</span><span>${i[1]}<br><b>${r[i[0]]!=null?r[i[0]]+' '+i[2]:'Not logged'}</b></span><span class="x" style="font-size:20px">+</span></button>`).join('')+`<div class="c"><h3>Stress level</h3><div style="display:flex;gap:8px">${['Low','Medium','High'].map(s=>`<button class="r ${r.stress===s?'s':''}" style="justify-content:center;margin:0" onclick="dr(life.d).stress='${s}';save();render()">${s}</button>`).join('')}</div></div><p>These are your own logs. No conclusions are drawn from them automatically.</p>`},
/* ---- medication ---- */
med(){med.t=med.t||'med';const L=S.meds.filter(m=>m.type===med.t);return hd('Medication & Supplements')+`<div class="seg"><button class="${med.t==='med'?'s':''}" onclick="med.t='med';render()">Medication</button><button class="${med.t==='sup'?'s':''}" onclick="med.t='sup';render()">Supplements</button></div>${L.length?L.map(m=>`<div class="r" style="cursor:default"><span class="i">◷</span><span style="flex:1">${esc(m.name)}<br><small>${esc(m.freq)}${m.dose?' · '+esc(m.dose):''}${m.rem?' · reminder '+esc(m.rem):''}</small></span><button class="tg ${m.on?'on':''}" onclick="tgm('${m.id}')" aria-label="Enabled" role="switch" aria-checked="${!!m.on}"></button><button class="ic" style="font-size:14px" onclick="delM('${m.id}')" aria-label="Delete">✕</button></div>`).join(''):'<div class="c"><p>Nothing added yet.</p></div>'}<button class="b o" onclick="addM()">+ Add ${med.t==='med'?'medication':'supplement'}</button><p style="margin-top:10px">This tracker only records what you enter. It does not recommend, start, stop or change any medication.</p>`},
/* ---- learn ---- */
learn(){learn.c=learn.c||'All';const A=ART.filter(a=>learn.c==='All'||a.c===learn.c);return hd('Learn')+`<div class="tabs">${['All','Period','Cycle','PCOS','Self-care'].map(c=>`<button class="ch ${learn.c===c?'s':''}" onclick="learn.c='${c}';render()">${c}</button>`).join('')}</div>${A.map(a=>`<button class="r" onclick="art(${ART.indexOf(a)})"><span class="i">▤</span><span>${a.t}<br><small>${a.m} min read</small></span><span class="x">›</span></button>`).join('')}<p>Educational content only. It is not personal advice or a prediction.</p>`},
/* ---- settings ---- */
set(){return hd('Settings')+`<div class="c"><label style="margin:0">Your name</label><input value="${esc(S.set.name)}" placeholder="Name (optional)" onchange="S.set.name=this.value.trim();save();toast('Saved.')"></div>`+[['cyc','Cycle preferences','◔'],['notif','Trackers & reminders','◎'],['priv','Privacy & security','🔒'],['data','Backup & data management','▤'],['look','App appearance','◐'],['help','Help & support','?'],['about','About','i']].map(x=>`<button class="r" onclick="go('sub','${x[0]}')"><span class="i">${x[2]}</span>${x[1]}<span class="x">›</span></button>`).join('')},
sub(k){return SUB[k]()},
lock(){return`<div class="ob" style="align-items:center;text-align:center"><div class="sp"></div><span class="hx" aria-hidden="true"></span><h2 style="margin-top:16px">App locked</h2><p>Enter your PIN to continue.</p><input id="pin" type="password" inputmode="numeric" maxlength="8" autocomplete="off" aria-label="PIN" style="max-width:200px;text-align:center;letter-spacing:8px;margin-top:14px" onkeydown="if(event.key==='Enter')unlock()"><button class="b" style="max-width:200px" onclick="unlock()">Unlock</button><p style="margin-top:14px;font-size:11px;max-width:260px">Fingerprint unlock isn't available in a web app. The PIN is a local privacy screen, not device-level security.</p><div class="sp"></div></div>`},
ob(){return OBS[S.ob]()}};
const LP={};const cal={},ins={},jour={},sym={},med={},learn={};
const tg=(a,v)=>{const i=a.indexOf(v);i>-1?a.splice(i,1):a.push(v)};
const chart=(l,u='Cycle length (days)')=>{if(l.length<2)return'';const W=290,H=110,mx=Math.max(...l)+5,mn=Math.min(...l)-5,X=i=>20+i*(W-40)/(l.length-1),Y=v=>H-14-(v-mn)/(mx-mn||1)*(H-34);return`<svg viewBox="0 0 ${W} ${H}" width="100%" role="img" aria-label="${u}: ${l.join(', ')}"><polyline fill="none" stroke="var(--ac)" stroke-width="2" points="${l.map((v,i)=>X(i)+','+Y(v)).join(' ')}"/>${l.map((v,i)=>`<circle cx="${X(i)}" cy="${Y(v)}" r="3.5" fill="var(--ac)"/><text x="${X(i)}" y="${Y(v)-8}" text-anchor="middle" font-size="10" fill="var(--tx)">${v}</text>`).join('')}</svg><small>${u}, oldest to newest</small>`};
const bars=(l,p)=>{const m=Math.max(...l);return`<div class="${p?'':'c'}">${p?'':'<h3>Recent cycles</h3>'}${l.map(v=>`<div style="display:flex;align-items:center;gap:10px;margin:7px 0"><span style="width:60px">${v} days</span><div class="bar"><i style="width:${v/m*100}%"></i></div></div>`).join('')}</div>`};
function quick(k){const d=today(),r=dr(d);if(k==='sym')return go('sym',d);if(k==='flow'){return sheet(`<h3>Flow today</h3>${['Light','Medium','Heavy'].map(f=>`<button class="r ${r.flow===f?'s':''}" onclick="dr('${d}').flow='${f}';save();shut();render();toast('Flow saved.')">${f}</button>`).join('')}`)}
const L=k==='mood'?MOODS:['None','Mild','Moderate','Severe'];sheet(`<h3>${k==='mood'?'How are you feeling?':'Pain today'}</h3>${L.map(x=>`<button class="r ${r[k]===x?'s':''}" onclick="dr('${d}').${k}='${x}';save();shut();render();toast('Saved.')">${x}</button>`).join('')}${k==='pain'?'<p>Logging pain does not identify a cause. If pain is unusually severe, consider seeking medical advice.</p>':''}`)}
function dayS(d){if(d>today()){const E=eDays();return sheet(`<h3>${fs(d,{weekday:'long',month:'long',day:'numeric'})}</h3><p>${E.has(d)?'<b>Estimated</b> period window — not confirmed.':'This day has not happened yet.'} You can log symptoms and mood once the day arrives.</p><button class="b o" onclick="shut()">Close</button>`)}const P=pDays(),E=eDays(),r=S.daily[d],p=S.periods.find(x=>d>=x.startDate&&d<=(x.endDate||x.startDate));
sheet(`<h3>${fs(d,{weekday:'long',month:'long',day:'numeric'})}</h3><p>${p?'<b style="color:var(--ac2)">Logged:</b> period ('+p.flow+' flow)':E.has(d)?'<b>Estimated</b> period window — not confirmed':'Nothing marked for this day.'}</p>${r?`<p>${r.mood?'Mood: '+r.mood+'. ':''}${r.pain?'Pain: '+r.pain+'. ':''}${r.symptoms.length?'Symptoms: '+r.symptoms.map(x=>esc(x)+(r.sev&&r.sev[x]?' ('+r.sev[x]+')':'')).join(', ')+'.':''}</p>`:''}${qs(d,r)}<h3 style="margin-top:12px">Mood</h3><div>${MOODS.map(m=>`<button class="ch ${r&&r.mood===m?'s':''}" onclick="dr('${d}').mood='${m}';save();dayS('${d}');render()">${m}</button>`).join('')}</div><h3>Pain</h3><div>${['None','Mild','Moderate','Severe'].map(m=>`<button class="ch ${r&&r.pain===m?'s':''}" onclick="dr('${d}').pain='${m}';save();dayS('${d}')">${m}</button>`).join('')}</div><h3>Flow</h3><div>${['Light','Medium','Heavy'].map(m=>`<button class="ch ${r&&r.flow===m?'s':''}" onclick="dr('${d}').flow='${m}';save();dayS('${d}')">${m}</button>`).join('')}</div>${bl(d,r)}<label>Note</label><textarea id="dn" rows="2">${r?esc(r.notes):''}</textarea><button class="b o" onclick="dr('${d}').notes=document.getElementById('dn').value;save();shut();render();toast('Saved.')">Save note</button><div style="display:flex;gap:8px"><button class="b o" onclick="shut();go('sym','${d}')">Symptoms</button><button class="b o" onclick="shut();LP.p=null;go('log');setTimeout(()=>{LP.p.startDate='${d}';render()},0)">${p?'Log another':'Log period'}</button></div>${p?`<button class="b d" onclick="shut();LP.p=null;go('log','${p.id}')">Edit logged period</button>`:''}`)}
function saveP(){const p=LP.p;if(!p.startDate||isNaN(s2d(p.startDate)))return toast('Please choose a valid start date.');if(p.startDate>today())return toast('Start date cannot be in the future.');if(p.endDate&&p.endDate<p.startDate)return toast('End date cannot be before start date.');if(p.endDate&&diff(p.startDate,p.endDate)>20)return toast('Period length looks unusually long. Please check the dates.');
const e=p.endDate||p.startDate;if(S.periods.some(x=>x.id!==LP.id&&p.startDate<=(x.endDate||x.startDate)&&e>=x.startDate))return toast('This overlaps a period you already logged.');
if(p.endDate&&diff(p.startDate,p.endDate)+1>S.set.cyc)return toast('Period length exceeds your cycle length. Please check.');
if(LP.id){Object.assign(S.periods.find(x=>x.id===LP.id),p,{updatedAt:Date.now()})}else S.periods.push({...p,id:'p'+Date.now(),endDate:p.endDate||null,createdAt:Date.now(),updatedAt:Date.now()});
p.symptoms.forEach(s=>{const r=dr(p.startDate);if(!r.symptoms.includes(s))r.symptoms.push(s)});save();LP.p=null;toast('Period saved.');hist=[];go('home')}
function delP(id){S.periods=S.periods.filter(p=>p.id!==id);save();shut();LP.p=null;toast('Period deleted.');hist=[];go('home')}
function addCustom(cb){sheet(`<h3>Add symptom</h3><input id="cs" maxlength="30" placeholder="Symptom name"><button class="b" onclick="const v=document.getElementById('cs').value.trim();if(!v)return toast('Enter a name.');if(!S.custom.includes(v)&&!SY.includes(v))S.custom.push(v);save();shut();(${cb})(v)">Add</button>`)}
function ask(k,l,u){sheet(`<h3>${l} (${u})</h3><input id="av" type="number" inputmode="decimal" step="any" min="0" value="${dr(life.d)[k]??''}"><button class="b" onclick="const v=parseFloat(document.getElementById('av').value);if(isNaN(v)||v<0||v>${k==='sleep'?24:k==='water'?20:k==='exercise'?1440:500})return toast('Enter a sensible number.');dr(life.d).${k}=v;save();shut();render();toast('Saved.')">Save</button>`)}
function saveJ(){const d=jour.d||today(),t=document.getElementById('jt').value.trim();if(!t&&!jour.m)return toast('Add a mood or a note first.');S.journal[d]={date:d,mood:jour.m||null,text:t};dr(d).mood=jour.m||dr(d).mood;save();toast('Journal entry saved.');render()}
function delJ(d){delete S.journal[d];jour.m=undefined;save();toast('Journal entry deleted.');render()}
const jlist=L=>L.length?L.map(e=>`<button class="r" onclick="jour.d='${e.date}';jour.m=undefined;render()"><span style="flex:1"><b>${fs(e.date,{month:'short',day:'numeric',year:'numeric'})}</b> ${e.mood?'· '+e.mood:''}<br><small>${esc(e.text.slice(0,70))}</small></span><span class="x">›</span></button>`).join(''):'<p>No journal entries yet. Write your first one above.</p>';
function jl(){const q=jour.q.toLowerCase();$('#jl').innerHTML=jlist(Object.values(S.journal).filter(x=>(x.text+x.mood+x.date).toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date)))}
function addM(){sheet(`<h3>Add ${med.t==='med'?'medication':'supplement'}</h3><label>Name</label><input id="mn" maxlength="40"><label>Dose (optional)</label><input id="md"><label>Frequency</label><select id="mf"><option>Daily</option><option>Twice daily</option><option>Weekly</option><option>As needed</option></select><label>Reminder time (optional)</label><input id="mr" type="time"><button class="b" onclick="const n=document.getElementById('mn').value.trim();if(!n)return toast('Enter a name.');S.meds.push({id:'m'+Date.now(),type:med.t,name:n,dose:document.getElementById('md').value.trim(),freq:document.getElementById('mf').value,rem:document.getElementById('mr').value,on:true});save();shut();render();toast('Saved.')">Save</button>`)}
const tgm=id=>{const m=S.meds.find(x=>x.id===id);m.on=!m.on;save();render()},delM=id=>{S.meds=S.meds.filter(x=>x.id!==id);save();render();toast('Removed.')};
const ART=[{c:'Cycle',t:'What happens during a menstrual cycle?',m:5,b:['A menstrual cycle is counted from the first day of one period to the first day of the next. Its length differs between people and can change over time.','Broadly, it includes bleeding, a phase when the uterine lining rebuilds, ovulation (when an egg may be released), and a phase before the next period.','Ovulation timing varies a lot, so calendar-based estimates are only estimates.']},{c:'PCOS',t:'PCOS: what you need to know',m:6,b:['Polycystic ovary syndrome (PCOS) is a common hormonal condition. It can be associated with irregular periods, acne, changes in hair growth and other symptoms.','It can only be diagnosed by a healthcare professional. This app does not diagnose PCOS, and logging a symptom does not mean you have it.','Tracking cycle lengths and symptoms can give you something concrete to discuss with a clinician.']},{c:'Cycle',t:'Irregular cycles: common reasons',m:6,b:['Cycles can vary because of stress, changes in sleep or weight, intense exercise, certain medications, breastfeeding, life stages such as puberty or perimenopause, and medical conditions.','A single irregular cycle is common. If your cycles stay unpredictable or you have been without a period for a long time, consider speaking with a healthcare professional.']},{c:'Period',t:'Period pain: when to seek medical advice',m:4,b:['Mild to moderate cramps are common. Pain that is unusually severe, is getting worse, keeps you from daily activities, or comes with very heavy bleeding, fainting or dizziness is worth discussing with a healthcare professional.','If something feels unusual for you, you do not need to wait to ask for advice.']},{c:'Cycle',t:'How cycle tracking works',m:4,b:['This app measures a cycle as the gap between the start dates you log. Averages use your most recent cycles.','With regular cycles it gives a single estimated date. When your cycles vary, it shows a range instead, because a single date would be misleading.','Everything marked “Estimated” is a prediction, not a confirmed event.']},{c:'Self-care',t:'Sleep, movement and stress: gentle habits',m:4,b:['Regular sleep, movement you enjoy, and ways to manage stress support general wellbeing for many people.','Tracking these alongside symptoms can help you notice patterns, but patterns in your log do not prove that one thing causes another.']}];
const art=i=>{const a=ART[i];sheet(`<h3 style="font-family:var(--ser);font-size:19px">${a.t}</h3><small>${a.m} min read · Educational</small>${a.b.map(t=>`<p style="color:var(--tx);margin:10px 0">${t}</p>`).join('')}<button class="b o" onclick="shut()">Close</button>`)};
const tgr=(k)=>`<button class="tg ${S.set[k]?'on':''}" role="switch" aria-checked="${!!S.set[k]}" onclick="tset('${k}')"></button>`;
function tset(k){S.set[k]=!S.set[k];if(k==='notif'&&S.set.notif&&'Notification'in window)Notification.requestPermission();save();render()}
const row=(t,x)=>`<div class="r" style="cursor:default">${t}<span class="x">${x}</span></div>`;
const SUB={cyc:()=>hd('Cycle preferences')+`<div class="c"><label style="margin:0">Cycle type</label><select onchange="S.set.type=this.value;save();toast('Saved.')">${TY.map(t=>`<option value="${t[0]}" ${S.set.type===t[0]?'selected':''}>${t[1]}</option>`).join('')}</select><label>Usual cycle length (days)</label><input id="sc" type="number" min="15" max="90" value="${S.set.cyc}"><label>Usual period length (days)</label><input id="sp" type="number" min="1" max="14" value="${S.set.per}"><button class="b" onclick="const c=+sc.value,p=+sp.value;if(!(c>=15&&c<=90))return toast('Cycle length must be 15–90 days.');if(!(p>=1&&p<=14))return toast('Period length must be 1–14 days.');if(p>c)return toast('Period cannot be longer than the cycle.');S.set.cyc=c;S.set.per=p;save();toast('Preferences saved.')">Save</button></div><p>Predictions use your logged start dates once you have them. These values are only used as a starting point.</p>`,
notif:()=>hd('Trackers & reminders')+`<div class="c">${row('Fertility tracking',tgr('fert'))}${row('Pregnancy mode',tgr('preg'))}${row('Browser notifications',tgr('notif'))}</div><h3>Reminders</h3>${S.rem.length?S.rem.map(r=>`<div class="r" style="cursor:default"><span style="flex:1">${esc(r.label)}<br><small>${RT[r.type]} · ${r.type==='period'?'day before, ':''}${r.time}</small></span><button class="tg ${r.on?'on':''}" role="switch" aria-checked="${!!r.on}" onclick="tgR('${r.id}')"></button><button class="ic" style="font-size:14px" onclick="delR('${r.id}')" aria-label="Delete">✕</button></div>`).join(''):'<div class="c"><p>No reminders yet.</p></div>'}<button class="b o" onclick="addR()">Add reminder</button><p style="margin-top:8px">Reminders are optional and never include health details: they only say “You have a reminder from your health tracker.” Because this runs in a web page, they fire only while the app is open in your browser.</p><h3 style="margin-top:12px">Tracking preferences</h3>${TR.map(t=>`<button class="r ${S.set.track.includes(t)?'s':''}" onclick="tg(S.set.track,'${t}');save();render()"><span>${t}</span><span class="x" style="color:var(--ac);font-weight:700">${S.set.track.includes(t)?'✓':''}</span></button>`).join('')}`,
priv:()=>hd('Privacy & security')+`<div class="c"><h3>App lock (PIN)</h3><p>${S.set.pin?'A PIN is set.':'No PIN set.'} The PIN is a local privacy screen on this browser. It is not encryption and not device-level security. Fingerprint unlock is not available to web apps.</p><input id="np" type="password" inputmode="numeric" maxlength="8" placeholder="New PIN (4–8 digits)"><button class="b" onclick="setPin()">${S.set.pin?'Change PIN':'Set PIN'}</button>${S.set.pin?'<button class="b d" onclick="S.set.pin=null;save();toast(\'PIN removed.\');render()">Remove PIN</button><button class="b o" onclick="go(\'lock\')">Lock now</button>':''}</div><p>Your data stays on this device. No account, no server, no analytics.</p>`,
data:()=>hd('Data management')+`<div class="c"><button class="b o" style="margin:0" onclick="exp()">Export data (JSON)</button><label>Import data</label><input type="file" id="imp" accept="application/json" onchange="imp(this)"><button class="b d" onclick="sheet('<h3>Delete all health data?</h3><p>Every period, log, journal entry and setting will be removed from this device.</p><button class=\\'b\\' onclick=\\'del2()\\'>Continue</button><button class=\\'b g\\' onclick=\\'shut()\\'>Cancel</button>')">Delete all data</button></div>`,
look:()=>hd('App appearance')+['dark','light','system'].map(t=>`<button class="r ${S.set.theme===t?'s':''}" onclick="S.set.theme='${t}';save();render()"><span class="i">${S.set.theme===t?'✓':'•'}</span>${t[0].toUpperCase()+t.slice(1)}${t==='system'?' default':' mode'}</button>`).join(''),
help:()=>hd('Help & support')+`<div class="c"><h3>When to seek medical help</h3><p>If something feels unusual for you or you are concerned, consider speaking with a healthcare professional. This is especially true for unusually severe pain, very heavy bleeding, fainting or dizziness with bleeding, worsening symptoms, or a very long absence of periods.</p></div><div class="c"><h3>Using the app</h3><p>Tap a calendar day to view or add information. Estimates are shown dashed and are never confirmed events. Export your data regularly from Data management if you want a backup.</p></div>`,
about:()=>hd('About')+`<div class="c" style="text-align:center"><span class="hx sm" style="margin:8px auto 12px" aria-hidden="true"></span><h2>Hospital</h2><p>A private, local-first cycle and health tracker. It is a tracking and educational tool. It does not diagnose conditions, confirm pregnancy or replace professional care.</p></div>`};
function setPin(){const v=document.getElementById('np').value;if(!/^\d{4,8}$/.test(v))return toast('PIN must be 4–8 digits.');S.set.pin=hp(v);save();toast('PIN set.');render()}
const hp=s=>{let h=5381;for(const c of 'ct'+s)h=(h*33^c.charCodeAt(0))>>>0;return h};
function unlock(){if(hp(document.getElementById('pin').value)===S.set.pin){cur='home';hist=[];render()}else{toast('Incorrect PIN.');document.getElementById('pin').value=''}}
function exp(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='health-tracker-export.json';a.click();toast('Your data has been exported.')}
function imp(el){const f=el.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d.set||!Array.isArray(d.periods)||typeof d.daily!=='object')throw 0;S=Object.assign(JSON.parse(JSON.stringify(DEF)),d);S.preg=S.preg||{on:false,lmp:'',notes:[]};S.rem=S.rem||[];save();toast('Data imported.');hist=[];go('home')}catch(e){toast('That file is not a valid export.')}};r.readAsText(f)}
function del2(){sheet(`<h3>Are you sure?</h3><p>Type DELETE to confirm. This cannot be undone.</p><input id="dc"><button class="b" onclick="if(document.getElementById('dc').value!=='DELETE')return toast('Type DELETE exactly.');localStorage.removeItem(DK);S=JSON.parse(JSON.stringify(DEF));S.preg={on:false,lmp:'',notes:[]};S.rem=[];shut();hist=[];Object.assign(OB,{t:[],dt:null});cur='ob';render();toast('All data deleted.')">Delete everything</button><button class="b g" onclick="shut()">Cancel</button>`)}

/* ---- v4 additions ---- */
Object.assign(PARENT,{preg:'more',sum:'more'});
const RT={period:'Expected period',log:'Daily logging',med:'Medication',water:'Hydration',custom:'Custom'};
function fert(){const s=new Set();if(!S.set.fert)return s;const e=est();if(!e)return s;for(let d=addD(e.lo,-19);d<=addD(e.range?e.hi:e.lo,-13);d=addD(d,1))s.add(d);return s}
const _home=V.home;V.home=function(){let h=_home();if(S.set.fert){const e=est(),f=[...fert()].sort();h+=`<div class="c"><h3>Fertility (estimated)</h3>${f.length?`<p style="color:var(--tx)">Estimated fertile window: ${fs(f[0])}–${fs(f[f.length-1])}</p>`:'<p>Log a period to see an estimated window.</p>'}<p>Predictions may be less reliable with irregular cycles. This is not confirmed ovulation, and it cannot tell you when it is safe or unsafe to conceive. You can turn this off in Trackers &amp; reminders.</p></div>`}return h};
function addR(){sheet(`<h3>Add reminder</h3><label>Type</label><select id="rt">${Object.entries(RT).map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select><label>Label (optional)</label><input id="rl" maxlength="40"><label>Time</label><input id="rm" type="time" value="09:00"><button class="b" onclick="const t=document.getElementById('rm').value;if(!t)return toast('Choose a time.');const y=document.getElementById('rt').value;S.rem.push({id:'r'+Date.now(),type:y,label:document.getElementById('rl').value.trim()||RT[y],time:t,on:true});save();shut();render();toast('Reminder saved.')">Save</button>`)}
const tgR=id=>{const r=S.rem.find(x=>x.id===id);r.on=!r.on;save();render()},delR=id=>{S.rem=S.rem.filter(x=>x.id!==id);save();render();toast('Reminder deleted.')};
const fired={};function notify(){toast('You have a reminder from your health tracker.');try{if(S.set.notif&&'Notification' in window&&Notification.permission==='granted')new Notification('Health tracker',{body:'You have a reminder from your health tracker.'})}catch(e){}}
setInterval(()=>{if(S.ob<99)return;const n=new Date(),hm=pad(n.getHours())+':'+pad(n.getMinutes());S.rem.forEach(r=>{if(!r.on||r.time!==hm)return;if(r.type==='period'){const e=est();if(!e||addD(today(),1)!==e.lo)return}const k=r.id+today()+hm;if(fired[k])return;fired[k]=1;notify()});S.meds.forEach(m=>{if(m.on&&m.rem===hm){const k=m.id+today()+hm;if(!fired[k]){fired[k]=1;notify()}}})},20000);
V.preg=function(){const p=S.preg;let b;if(!p.on){b=`<div class="c"><h3>Pregnancy tracking</h3><p>This is a separate mode. The app never assumes pregnancy from a late period and cannot confirm or diagnose it. A test or a healthcare professional can confirm.</p><label>First day of last period (or the date your clinician gave you)</label><input type="date" id="pl" max="${today()}"><button class="b" onclick="const v=document.getElementById('pl').value;if(!v||isNaN(s2d(v)))return toast('Choose a valid date.');if(v>today())return toast('Date cannot be in the future.');if(diff(v,today())>300)return toast('That date is too far back.');S.preg.on=true;S.preg.lmp=v;save();render();toast('Pregnancy tracking started.')">Start tracking</button></div>`}
else{const d=diff(p.lmp,today()),w=Math.floor(d/7);b=`<div class="c" style="text-align:center"><small>Estimated</small><h1>Week ${w}</h1><p>${d%7} day${d%7==1?'':'s'} into this week</p><p style="color:var(--tx)">Estimated due date: ${fs(addD(p.lmp,280),{month:'long',day:'numeric',year:'numeric'})}</p><p>Counted from the date you entered. Your clinician's dating may differ.</p></div><div class="c"><h3>Notes</h3><textarea id="pn" rows="3" placeholder="Appointments, symptoms, questions for your clinician"></textarea><button class="b" onclick="const t=document.getElementById('pn').value.trim();if(!t)return toast('Write a note first.');S.preg.notes.unshift({d:today(),t});save();render();toast('Note saved.')">Save note</button>${p.notes.length?p.notes.map((n,i)=>`<div class="r" style="cursor:default;margin-top:8px"><span style="flex:1"><b>${fs(n.d)}</b><br><small>${esc(n.t)}</small></span><button class="ic" style="font-size:14px" onclick="S.preg.notes.splice(${i},1);save();render()" aria-label="Delete note">✕</button></div>`).join(''):'<p style="margin-top:8px">No notes yet.</p>'}</div><button class="b d" onclick="sheet('<h3>Stop pregnancy tracking?</h3><p>Your notes here will be removed.</p><button class=\'b\' onclick=\'S.preg={on:false,lmp:&quot;&quot;,notes:[]};save();shut();render()\'>Stop tracking</button><button class=\'b g\' onclick=\'shut()\'>Cancel</button>')">Stop tracking</button>`}
return hd('Pregnancy')+b+'<p>If you have concerns about your health or pregnancy, please speak with a healthcare professional.</p>'};
function trends(){const c=cy();let h='';const pn={};Object.values(S.daily).forEach(r=>r.pain&&(pn[r.pain]=(pn[r.pain]||0)+1));const pe=Object.entries(pn);
h+=`<div class="c"><h3>Pain you logged</h3>${pe.length?pe.map(x=>`<div style="margin-bottom:8px"><small>${x[0]} · ${x[1]} day${x[1]>1?'s':''}</small><div class="bar"><i style="width:${x[1]/Math.max(...pe.map(y=>y[1]))*100}%"></i></div></div>`).join('')+'<p>This shows what you logged and does not identify a cause.</p>':'<p>No pain logged yet.</p>'}</div>`;
const du=S.periods.filter(p=>p.endDate).sort((a,b)=>a.startDate.localeCompare(b.startDate)).slice(-6).map(p=>diff(p.startDate,p.endDate)+1);
h+=`<div class="c"><h3>Period duration</h3>${du.length>1?chart(du,'Period length (days)'):du.length?`<p>Your logged period lasted ${du[0]} days.</p>`:'<p>Log a period with an end date to see durations.</p>'}</div>`;
[['sleep','Sleep (h)'],['water','Water (L)'],['exercise','Exercise (min)'],['weight','Weight (kg)']].forEach(k=>{const l=Object.values(S.daily).filter(r=>r[k[0]]!=null).sort((a,b)=>a.date.localeCompare(b.date)).slice(-10).map(r=>r[k[0]]);h+=`<div class="c"><h3>${k[1]}</h3>${l.length>1?chart(l,k[1])+'<p>Your recent records show these values. No conclusions are drawn from them.</p>':'<p>Log at least two days in Lifestyle to see a trend.</p>'}</div>`});return h}
function sumData(){const c=cy(),f={};Object.values(S.daily).forEach(r=>r.symptoms.forEach(x=>f[x]=(f[x]||0)+1));const sy=Object.entries(f).sort((a,b)=>b[1]-a[1]).slice(0,8),ds=Object.values(S.daily),last=k=>{const l=ds.filter(r=>r[k]!=null).sort((a,b)=>a.date.localeCompare(b.date));return l.length?l[l.length-1][k]:null},pn={};ds.forEach(r=>r.pain&&(pn[r.pain]=(pn[r.pain]||0)+1));
return[['Overview',['Generated: '+fs(today(),{month:'long',day:'numeric',year:'numeric'}),'Cycle type (self-selected): '+S.set.type,'Logged periods: '+c.n]],['Cycle lengths',c.lens.length?['Recent lengths (days): '+c.lens.slice(-8).join(', '),'Average '+c.avg+', median '+c.med+', shortest '+c.mn+', longest '+c.mx,'Average period length: '+c.ap+' days']:['Not enough logged periods yet.']],['Recent periods',S.periods.slice().sort((a,b)=>b.startDate.localeCompare(a.startDate)).slice(0,6).map(p=>fs(p.startDate,{month:'short',day:'numeric',year:'numeric'})+(p.endDate?' to '+fs(p.endDate,{month:'short',day:'numeric'}):'')+', flow '+p.flow).concat(S.periods.length?[]:['None logged.'])],['Symptoms logged (days)',sy.length?sy.map(x=>x[0]+': '+x[1]):['None logged.']],['Pain logged',Object.keys(pn).length?Object.entries(pn).map(x=>x[0]+': '+x[1]+' day(s)'):['None logged.']],['Medication & supplements',S.meds.length?S.meds.map(m=>m.name+(m.dose?' '+m.dose:'')+', '+m.freq+(m.on?'':' (paused)')):['None recorded.']],['Latest lifestyle entries',['Sleep: '+(last('sleep')??'–')+' h','Water: '+(last('water')??'–')+' L','Exercise: '+(last('exercise')??'–')+' min','Weight: '+(last('weight')??'–')+' kg']],['Note',['Self-recorded data from a tracking app. It is not a diagnosis and may be incomplete.']]]}
V.sum=function(){return hd('Doctor summary')+'<p style="margin:-6px 0 12px">A one-page summary of what you logged, to share with a healthcare professional if you choose.</p>'+sumData().map(x=>`<div class="c"><h3>${x[0]}</h3>${x[1].map(l=>`<p style="color:var(--tx)">${esc(l)}</p>`).join('')}</div>`).join('')+'<button class="b" onclick="dlSum()">Download summary (printable)</button><button class="b o" onclick="cpSum()">Copy as text</button>'};
function dlSum(){const h='<!DOCTYPE html><meta charset="utf-8"><title>Health summary</title><style>body{font:14px/1.5 Georgia,serif;max-width:680px;margin:30px auto;padding:0 16px;color:#2b1d14}h1{color:#86512f}h2{font-size:15px;border-bottom:1px solid #ecdfd1;padding-bottom:3px;margin-top:20px}button{margin:10px 0;padding:8px 14px}@media print{button{display:none}}</style><h1>Health summary</h1><button onclick="print()">Print or save as PDF</button>'+sumData().map(x=>'<h2>'+esc(x[0])+'</h2>'+x[1].map(l=>'<div>'+esc(l)+'</div>').join('')).join('');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([h],{type:'text/html'}));a.download='health-summary.html';a.click();toast('Summary downloaded.')}
function cpSum(){const t=sumData().map(x=>x[0]+'\n'+x[1].join('\n')).join('\n\n');try{navigator.clipboard.writeText(t).then(()=>toast('Summary copied.'),()=>toast('Copy not allowed here. Use Download.'))}catch(e){toast('Copy not allowed here. Use Download.')}}

const life={d:null};
function pastDay(){sheet(`<h3>Log a different date</h3><p>Add symptoms, mood, pain, flow or notes for any earlier day.</p><input type="date" id="pd" max="${today()}" value="${addD(today(),-1)}"><button class="b" onclick="const v=document.getElementById('pd').value;if(!v||isNaN(s2d(v))||v>today())return toast('Choose today or an earlier date.');dayS(v)">Open this day</button>`)}

/* ---- v5: severity, bleeding detail, quick logging, encrypted backup ---- */
const sevRow=(d,s,r)=>`<div style="display:flex;gap:6px;margin:-2px 0 10px 8px">${['Mild','Moderate','Severe'].map(l=>`<button class="ch ${r.sev&&r.sev[s]===l?'s':''}" style="margin:0" onclick="setSev('${d}','${encodeURIComponent(s)}','${l}')">${l}</button>`).join('')}</div>`;
function setSev(d,s,l){const r=dr(d);r.sev=r.sev||{};r.sev[decodeURIComponent(s)]=l;save();render()}
function topSym(){const f={};Object.values(S.daily).forEach(r=>r.symptoms.forEach(x=>f[x]=(f[x]||0)+1));const t=Object.entries(f).sort((a,b)=>b[1]-a[1]).map(x=>x[0]);['Cramps','Fatigue','Headache','Bloating'].forEach(x=>{if(!t.includes(x))t.push(x)});return t.slice(0,4)}
function qs(d,r){const p=addD(d,-1),hp=S.daily[p]&&(S.daily[p].symptoms.length||S.daily[p].mood||S.daily[p].pain);return`<h3 style="margin-top:12px">Quick symptoms</h3><div>${topSym().map(x=>`<button class="ch ${r&&r.symptoms.includes(x)?'s':''}" onclick="qsT('${d}','${encodeURIComponent(x)}')">${esc(x)}</button>`).join('')}<button class="ch" onclick="shut();go('sym','${d}')">More…</button></div>${hp?`<button class="b o" style="margin:2px 0 4px" onclick="copyPrev('${d}')">Same as the day before</button>`:''}`}
function qsT(d,x){tg(dr(d).symptoms,decodeURIComponent(x));save();dayS(d);render()}
function copyPrev(d){const p=S.daily[addD(d,-1)];if(!p)return;const r=dr(d);r.symptoms=[...p.symptoms];r.sev=p.sev?{...p.sev}:undefined;if(p.mood)r.mood=p.mood;if(p.pain)r.pain=p.pain;save();dayS(d);render();toast('Copied from the day before. Edit anything that differs.')}
function bl(d,r){return`<h3>Bleeding detail</h3><div><button class="ch ${r&&r.spot?'s':''}" onclick="dr('${d}').spot=!dr('${d}').spot;save();dayS('${d}');render()">Spotting</button><button class="ch ${r&&r.clots?'s':''}" onclick="dr('${d}').clots=!dr('${d}').clots;save();dayS('${d}')">Clots</button></div>`}
function pastDay(){const days=[...Array(7)].map((_,i)=>addD(today(),-i)),lg=d=>{const r=S.daily[d];return r&&(r.symptoms.length||r.mood||r.pain||r.notes||r.flow||r.spot)};sheet(`<h3>Log a different date</h3><p>Tap a day from the past week, or choose any earlier date.</p><div>${days.map(d=>`<button class="ch ${lg(d)?'s':''}" onclick="dayS('${d}')">${fs(d,{weekday:'short',day:'numeric'})}${lg(d)?' ✓':''}</button>`).join('')}</div><label>Any earlier date</label><input type="date" id="pd" max="${today()}" value="${addD(today(),-8)}"><button class="b" onclick="const v=document.getElementById('pd').value;if(!v||isNaN(s2d(v))||v>today())return toast('Choose today or an earlier date.');dayS(v)">Open this day</button>`)}
const _sd=sumData;sumData=function(){const a=_sd(),ds=Object.values(S.daily),c=cy(),sv={};ds.forEach(r=>r.symptoms.forEach(x=>{const k=x+(r.sev&&r.sev[x]?' ('+r.sev[x]+')':'');sv[k]=(sv[k]||0)+1}));
const bd=ds.filter(r=>r.flow).length,sp=ds.filter(r=>r.spot).length,cl=ds.filter(r=>r.clots).length,hv=ds.filter(r=>r.flow==='Heavy').length,sevP=ds.filter(r=>r.pain==='Severe').length,out=c.lens.filter(l=>l<21||l>35).length,lp=S.periods.filter(p=>p.endDate&&diff(p.startDate,p.endDate)+1>7).length;
const pts=[];if(out)pts.push(out+' of '+c.lens.length+' logged cycles were shorter than 21 or longer than 35 days.');if(lp)pts.push(lp+' logged period(s) lasted longer than 7 days.');if(hv)pts.push('Heavy flow was logged on '+hv+' day(s).');if(cl)pts.push('Clots were logged on '+cl+' day(s).');if(sevP)pts.push('Severe pain was logged on '+sevP+' day(s).');
const ex=[['Symptoms with severity (days)',Object.keys(sv).length?Object.entries(sv).sort((x,y)=>y[1]-x[1]).slice(0,12).map(x=>x[0]+': '+x[1]):['None logged.']],['Bleeding days logged',['Days with flow recorded: '+bd,'Spotting days: '+sp,'Days with clots noted: '+cl]],['Points that may be worth discussing',pts.length?pts.concat(['These are observations from your own log, not a diagnosis.']):['Nothing in your log crossed these simple checks. Discuss any concerns regardless.']]];a.splice(a.length-1,0,...ex);return a};
const _hm=V.home;V.home=function(){let h=_hm();const has=S.periods.length||Object.keys(S.daily).length;const y=addD(today(),-1);if(S.periods.length&&!S.daily[y]&&!S.daily[today()])h+=`<p style="text-align:center;margin:6px 0">No pressure to log every day. You can fill in earlier days anytime.</p>`;return h};
const b64=u=>btoa(String.fromCharCode(...new Uint8Array(u))),ub=t=>Uint8Array.from(atob(t),c=>c.charCodeAt(0));
async function kdf(p,salt){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},k,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
const dl=(n,t,m)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:m}));a.download=n;a.click()};
function exp(){dl('health-tracker-backup.json',JSON.stringify(S,null,2),'application/json');S.lastBackup=Date.now();save();toast('Backup downloaded. It is not encrypted, so keep it private.')}
function encAsk(){sheet('<h3>Encrypted backup</h3><p>Choose a passphrase. Without it the file cannot be opened, and it cannot be recovered if you forget it.</p><input id="xp" type="password" autocomplete="new-password" placeholder="Passphrase (6+ characters)"><button class="b" onclick="encGo()">Download encrypted backup</button><button class="b g" onclick="shut()">Cancel</button>')}
async function encGo(){const p=document.getElementById('xp').value;if(p.length<6)return toast('Use at least 6 characters.');try{const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await kdf(p,salt),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,new TextEncoder().encode(JSON.stringify(S)));dl('health-tracker-backup.encrypted.json',JSON.stringify({enc:1,salt:b64(salt),iv:b64(iv),data:b64(ct)}),'application/json');S.lastBackup=Date.now();save();shut();toast('Encrypted backup downloaded.')}catch(e){toast('Encryption is not available in this browser.')}}
const okDate=d=>typeof d==='string'&&/^\d{4}-\d\d-\d\d$/.test(d)&&!isNaN(s2d(d));
function applyImport(d){if(!d||typeof d.set!=='object'||!Array.isArray(d.periods)||typeof d.daily!=='object'||d.daily===null)throw 0;d.periods=d.periods.filter(p=>p&&okDate(p.startDate)&&(!p.endDate||(okDate(p.endDate)&&p.endDate>=p.startDate)));Object.keys(d.daily).forEach(k=>{if(!okDate(k)||typeof d.daily[k]!=='object'||!Array.isArray(d.daily[k].symptoms))delete d.daily[k]});S=Object.assign(JSON.parse(JSON.stringify(DEF)),d);S.set=Object.assign({},DEF.set,d.set);S.preg=S.preg||{on:false,lmp:'',notes:[]};S.rem=S.rem||[];S.v3=1;save();hist=[];go('home');toast('Data restored on this device.')}
function imp(el){const f=el.files[0];if(!f)return;if(f.size>5e6)return toast('That file is too large.');const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.enc){window._enc=d;return sheet('<h3>Encrypted backup</h3><p>Enter the passphrase you chose.</p><input id="xp" type="password" autocomplete="current-password"><button class="b" onclick="decGo()">Restore</button><button class="b g" onclick="shut()">Cancel</button>')}applyImport(d)}catch(e){toast('That file is not a valid backup.')}};r.readAsText(f)}
async function decGo(){try{const d=window._enc,k=await kdf(document.getElementById('xp').value,ub(d.salt)),pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:ub(d.iv)},k,ub(d.data));shut();applyImport(JSON.parse(new TextDecoder().decode(pt)))}catch(e){toast('Wrong passphrase or damaged file.')}}
SUB.data=()=>hd('Data management')+`<div class="c"><h3>Where your data lives</h3><p>Only in this browser on this device. There is no account, no cloud copy and no server, so nobody else can restore it for you. To move to a new phone, save a backup here and import it there.</p></div><div class="c"><button class="b o" style="margin:0" onclick="exp()">Backup file (not encrypted)</button><button class="b" onclick="encAsk()">Encrypted backup (recommended)</button><p style="margin-top:6px">${S.lastBackup?'Last backup: '+new Date(S.lastBackup).toLocaleDateString():'No backup yet.'}</p><label>Restore from a backup file</label><input type="file" id="imp" accept="application/json,.json" onchange="imp(this)"><button class="b d" onclick="sheet('<h3>Delete all health data?</h3><p>Every period, log, journal entry and setting will be removed from this device.</p><button class=\\'b\\' onclick=\\'del2()\\'>Continue</button><button class=\\'b g\\' onclick=\\'shut()\\'>Cancel</button>')">Delete all data</button></div>`;
const _pv=SUB.priv;SUB.priv=()=>_pv()+`<div class="c"><h3>Privacy check</h3><p>Stored: your logs, journal, settings and PIN check value, in this browser only.</p><p>Not used: accounts, servers, analytics, ads, cookies, location or external fonts and scripts. A security policy in the page blocks network requests.</p><p>Limits: data in the browser is not encrypted, and the PIN only hides the screen. Anyone who can open this browser profile could read the data. Use a device passcode, and use the encrypted backup for files.</p></div>`;
if(S.ob<99){cur='ob'}else if(S.set.pin){cur='lock'}
render();

/* ---- install / offline info ---- */
const APP_VERSION='1.0.0';
function installApp(){const e=window._installEvt;if(!e)return toast('Install is not available right now.');e.prompt();e.userChoice.finally(()=>{window._installEvt=null;render()})}
const _ab=SUB.about;SUB.about=()=>_ab()+(window._installEvt?'<button class="b" onclick="installApp()">Install app</button>':'')+`<div class="c"><h3>Offline &amp; install</h3><p>After the first load, every screen works without internet. Your data never leaves this device.</p><p>Version ${APP_VERSION}</p></div>`;
